# Generated by Django 5.0.4 on 2024-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_backendframework_dimension_measurementscale_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendframework',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
