# Generated by Django 5.0.4 on 2024-05-22 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_evaluation_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.project'),
        ),
    ]
