# Generated by Django 5.0.4 on 2024-06-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_metric_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='project',
        ),
        migrations.AddField(
            model_name='dimension',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='api.project'),
        ),
        migrations.AddField(
            model_name='metric',
            name='measurement',
            field=models.TextField(default='Default measurement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='where_to_find',
            field=models.TextField(default='Default where to find'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimension',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='metric',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.dimension'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
