# Generated by Django 5.0.4 on 2024-06-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dimension_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='user',
        ),
    ]
