# Generated by Django 5.0.4 on 2024-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dimension_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='score',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='name_project',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='weighted_score',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='dimension',
        ),
        migrations.AddField(
            model_name='dimension',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dimension',
            name='metrics',
            field=models.ManyToManyField(to='api.metric'),
        ),
        migrations.AddField(
            model_name='framework',
            name='dimensions',
            field=models.ManyToManyField(to='api.dimension'),
        ),
        migrations.AddField(
            model_name='metric',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='measurement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metric',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frameworks', models.ManyToManyField(to='api.framework')),
            ],
        ),
        migrations.DeleteModel(
            name='MetricScore',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
